"""Tests for ActionPlanner — prerequisite-based action filtering + concrete action generation."""

import pytest
from action_planner import ActionPlanner as GoalPlanner


@pytest.fixture
def planner():
    return GoalPlanner()


_EMPTY_STATE: dict = {
    "health": 80,
    "hunger": 80,
    "sanity": 150,
    "nearby_entities": [],
    "threats": [],
}


# ── Empty inventory (base get_valid_actions) ──────────────────────────────────


def test_empty_inv_always_valid_actions(planner):
    valid = planner.get_valid_actions({})
    assert "explore" in valid
    assert "idle" in valid
    assert "eat_food" in valid
    assert "run_from_enemy" in valid
    # gather_resource is no longer a base ACTION_SPEC — it's generated by get_concrete_actions
    assert "gather_resource" not in valid


def test_empty_inv_tool_actions_blocked(planner):
    valid = planner.get_valid_actions({})
    assert "chop_tree" not in valid
    assert "mine_rock" not in valid


def test_empty_inv_craft_actions_blocked(planner):
    valid = planner.get_valid_actions({})
    assert "craft_item:axe" not in valid
    assert "craft_item:pickaxe" not in valid


# ── Tool prerequisites ────────────────────────────────────────────────────────


def test_axe_unlocks_chop_tree(planner):
    assert "chop_tree" in planner.get_valid_actions({"axe": 1})


def test_pickaxe_unlocks_mine_rock(planner):
    assert "mine_rock" in planner.get_valid_actions({"pickaxe": 1})


def test_partial_craft_prereq_still_blocked(planner):
    # Need twig + flint; only have twig
    valid = planner.get_valid_actions({"twigs": 1})
    assert "craft_item:axe" not in valid


def test_exact_craft_prereqs_unlock_craft(planner):
    assert "craft_item:axe" in planner.get_valid_actions({"twigs": 1, "flint": 1})


def test_surplus_prereqs_still_valid(planner):
    assert "craft_item:axe" in planner.get_valid_actions({"twigs": 5, "flint": 3})


def test_craft_axe_suppressed_when_already_held(planner):
    """craft_item:axe must NOT appear when axe is already in inventory."""
    valid = planner.get_valid_actions({"twigs": 1, "flint": 1, "axe": 1})
    assert "craft_item:axe" not in valid


def test_craft_pickaxe_suppressed_when_already_held(planner):
    """craft_item:pickaxe must NOT appear when pickaxe is already in inventory."""
    valid = planner.get_valid_actions({"twigs": 2, "flint": 2, "pickaxe": 1})
    assert "craft_item:pickaxe" not in valid


def test_craft_torch_not_suppressed_when_already_held(planner):
    """Consumables like torch are NOT redundant_if_held — can craft more even if one exists."""
    valid = planner.get_valid_actions({"twigs": 2, "cutgrass": 2, "torch": 1})
    assert "craft_item:torch" in valid


# ── Alias normalisation ───────────────────────────────────────────────────────


def test_twig_alias_normalised_to_twigs(planner):
    # "twig" (singular) should be treated as "twigs"
    assert "craft_item:axe" in planner.get_valid_actions({"twig": 1, "flint": 1})


def test_rock_alias_normalised(planner):
    assert "mine_rock" in planner.get_valid_actions({"pickaxe": 1})


# ── Format helpers ────────────────────────────────────────────────────────────


def test_format_valid_actions_is_sorted_csv(planner):
    result = planner.format_valid_actions({})
    # Extract bare action names (strip cost annotations like "craft_item:axe (...)")
    parts = [p.strip().split(" (")[0] for p in result.split(",")]
    assert parts == sorted(parts)


# ── get_concrete_actions ──────────────────────────────────────────────────────


def test_concrete_always_includes_explore_and_idle(planner):
    actions = planner.get_concrete_actions({}, _EMPTY_STATE)
    flat = " ".join(actions)
    assert "explore" in flat
    assert "idle" in flat


def test_concrete_eat_food_lists_specific_item(planner):
    inv = {"berries": 3, "twigs": 2}
    actions = planner.get_concrete_actions(inv, _EMPTY_STATE)
    assert any("eat_food:berries" in a for a in actions)


def test_concrete_no_eat_food_when_no_edibles(planner):
    inv = {"twigs": 5, "flint": 3}
    actions = planner.get_concrete_actions(inv, _EMPTY_STATE)
    # Only the generic fallback "eat_food  (check inventory...)" may appear, NOT a specific target
    assert not any(a.startswith("eat_food:") for a in actions)


def test_concrete_pick_up_item_from_nearby(planner):
    state = dict(
        _EMPTY_STATE, nearby_entities=[{"name": "log", "type": "item", "distance": 4}]
    )
    actions = planner.get_concrete_actions({}, state)
    assert any("pick_up_item:log" in a for a in actions)


def test_concrete_gather_resource_from_harvestable(planner):
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[{"name": "sapling", "type": "plant", "distance": 6}],
    )
    actions = planner.get_concrete_actions({}, state)
    assert any("gather_resource:twigs" in a for a in actions)


def test_concrete_craft_action_includes_cost(planner):
    inv = {"twigs": 1, "flint": 1}
    actions = planner.get_concrete_actions(inv, _EMPTY_STATE)
    assert any("craft_item:axe" in a for a in actions)
    axe_line = next(a for a in actions if "craft_item:axe" in a)
    assert "twigs" in axe_line and "flint" in axe_line


def test_concrete_chop_tree_needs_axe(planner):
    inv_no_axe = {"twigs": 5, "flint": 5}
    inv_with_axe = {"axe": 1}
    without = planner.get_concrete_actions(inv_no_axe, _EMPTY_STATE)
    with_axe = planner.get_concrete_actions(inv_with_axe, _EMPTY_STATE)
    assert not any("chop_tree" in a for a in without)
    assert any("chop_tree" in a for a in with_axe)


def test_concrete_hostile_includes_attack_and_run(planner):
    state = dict(_EMPTY_STATE, threats=[{"name": "spider", "distance": 10}])
    actions = planner.get_concrete_actions({}, state)
    assert any("attack_enemy:spider" in a for a in actions)
    assert any("run_from_enemy" in a for a in actions)


# ── Real game-state nearby patterns (from live conversation log) ──────────────
#
# The Lua exporter uses:
#   type="other"        for loose ground items (seeds, flint) AND noise (snow, rain, flowers)
#   type="harvestable"  for saplings, grass, evergreens, berrybushes, etc.
#
# The builder must distinguish pickable items from ambient noise purely by name.

# Typical early-game nearby list: mostly noise, one "seeds" on the ground
_NEARBY_NOISE_PLUS_SEEDS = [
    {"type": "other", "name": "snow", "distance": 0},
    {"type": "other", "name": "rain", "distance": 0},
    {"type": "other", "name": "flower", "distance": 5.4},
    {"type": "other", "name": "seeds", "distance": 7.2},
    {"type": "other", "name": "flower", "distance": 7.3},
]


def test_seeds_type_other_produces_pickup(planner):
    """seeds with type='other' must appear as pick_up_item despite non-item type."""
    state = dict(_EMPTY_STATE, nearby_entities=_NEARBY_NOISE_PLUS_SEEDS)
    actions = planner.get_concrete_actions({}, state)
    assert any("pick_up_item:seeds" in a for a in actions)


def test_ambient_noise_does_not_produce_pickup(planner):
    """snow, rain, flower, robin etc. must NOT produce any action."""
    state = dict(_EMPTY_STATE, nearby_entities=_NEARBY_NOISE_PLUS_SEEDS)
    actions = planner.get_concrete_actions({}, state)
    flat = " ".join(actions)
    assert "pick_up_item:snow" not in flat
    assert "pick_up_item:rain" not in flat
    assert "pick_up_item:flower" not in flat


def test_flint_type_other_produces_pickup(planner):
    """flint on the ground has type='other' in real exports."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "other", "name": "flint", "distance": 24.9},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    assert any("pick_up_item:flint" in a for a in actions)


def test_evergreen_type_harvestable_produces_gather_log(planner):
    """evergreen with type='harvestable' + axe in inventory → gather_resource:log."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "harvestable", "name": "evergreen", "distance": 9.4},
        ],
    )
    actions = planner.get_concrete_actions({"axe": 1}, state)
    assert any("gather_resource:log" in a for a in actions)


def test_evergreen_blocked_without_axe(planner):
    """evergreen with no axe → gather_resource:log must NOT appear."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "harvestable", "name": "evergreen", "distance": 9.4},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    assert not any("gather_resource:log" in a for a in actions)


def test_loose_log_pickup_no_tool_needed(planner):
    """Loose log on ground (type='other') is pick_up_item without any tool."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "other", "name": "log", "distance": 6.0},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    assert any("pick_up_item:log" in a for a in actions)


def test_loose_rocks_pickup_no_tool_needed(planner):
    """Loose rocks on ground (type='other') is pick_up_item without any tool."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "other", "name": "rocks", "distance": 8.0},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    assert any("pick_up_item:rocks" in a for a in actions)


def test_rock_boulder_blocked_without_pickaxe(planner):
    """Standing boulder (rock1) needs pickaxe → gather_resource:rocks absent without it."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "harvestable", "name": "rock1", "distance": 12.0},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    assert not any("gather_resource:rocks" in a for a in actions)


def test_rock_boulder_allowed_with_pickaxe(planner):
    """Standing boulder (rock1) + pickaxe → gather_resource:rocks present."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "harvestable", "name": "rock1", "distance": 12.0},
        ],
    )
    actions = planner.get_concrete_actions({"pickaxe": 1}, state)
    assert any("gather_resource:rocks" in a for a in actions)


def test_sapling_type_harvestable_produces_gather_twigs(planner):
    """sapling with type='harvestable' → gather_resource:twigs."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "harvestable", "name": "sapling", "distance": 11.5},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    assert any("gather_resource:twigs" in a for a in actions)


def test_berrybush_type_harvestable_produces_gather_berries(planner):
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "harvestable", "name": "berrybush", "distance": 16.8},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    assert any("gather_resource:berries" in a for a in actions)


def test_duplicate_same_yield_deduplicated(planner):
    """Multiple saplings nearby → only ONE gather_resource:twigs entry."""
    state = dict(
        _EMPTY_STATE,
        nearby_entities=[
            {"type": "harvestable", "name": "sapling", "distance": 11.5},
            {"type": "harvestable", "name": "sapling", "distance": 17.0},
            {"type": "harvestable", "name": "sapling", "distance": 23.6},
        ],
    )
    actions = planner.get_concrete_actions({}, state)
    twigs_actions = [a for a in actions if "gather_resource:twigs" in a]
    assert len(twigs_actions) == 1


def test_full_realistic_nearby_list(planner):
    """Full realistic nearby list from live log — correct set of actions generated."""
    nearby = [
        {"type": "other", "name": "snow", "distance": 0},
        {"type": "other", "name": "rain", "distance": 0},
        {"type": "other", "name": "flower", "distance": 5.4},
        {"type": "other", "name": "seeds", "distance": 7.2},
        {"type": "other", "name": "flower", "distance": 7.3},
        {"type": "other", "name": "flies", "distance": 8.5},
        {"type": "harvestable", "name": "pighead", "distance": 8.5},
        {"type": "other", "name": "robin", "distance": 8.7},
        {"type": "harvestable", "name": "sapling", "distance": 11.5},
        {"type": "harvestable", "name": "evergreen", "distance": 11.7},
        {"type": "harvestable", "name": "berrybush", "distance": 16.8},
        {"type": "harvestable", "name": "grass", "distance": 17.6},
        {"type": "other", "name": "flint", "distance": 24.9},
        {"type": "harvestable", "name": "rabbithole", "distance": 26.2},
    ]
    state = dict(_EMPTY_STATE, nearby_entities=nearby)
    inv_with_axe = {"axe": 1}
    actions = planner.get_concrete_actions(inv_with_axe, state)
    flat = " ".join(actions)

    # ground items recognised despite type="other"
    assert any("pick_up_item:seeds" in a for a in actions)
    assert any("pick_up_item:flint" in a for a in actions)

    # harvestables correctly mapped (axe present for evergreen)
    assert any("gather_resource:twigs" in a for a in actions)  # sapling
    assert any("gather_resource:log" in a for a in actions)  # evergreen (axe required)
    assert any("gather_resource:berries" in a for a in actions)  # berrybush
    assert any("gather_resource:cutgrass" in a for a in actions)  # grass

    # ambient noise absent
    assert "pick_up_item:snow" not in flat
    assert "pick_up_item:rain" not in flat
    assert "pick_up_item:flower" not in flat
    assert "pick_up_item:flies" not in flat
    assert "pick_up_item:robin" not in flat

    # always-present fallbacks
    assert any("explore" == a for a in actions)
    assert any("idle" == a for a in actions)
